### PR TITLE
feat: relative propertyUrl based in project's URL

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by martinmaillard** [comment]
I tested it locally and don't see any difference in the properties. What is this addressing?

**Comment by tpluscode** [comment]
It applies the baseUrl to `csvw:propertyUrl`.

**Comment by martinmaillard** [comment]
It still looks wrong for me. Is there any data migration I have to do? Should I start with a fresh triplestore?

Screenshot 2020-01-16 at 10 29 20

**Comment by tpluscode** [comment]
No migration. Maybe that project does not have a base URI set?

**Comment by martinmaillard** [comment]
It does, I just created it. Let me do everything from scratch 😄

**Comment by martinmaillard** [comment]
Still not working :(

The `csvw:aboutUrl` looks ok, but not `csvw:propertyUrl`.

**Comment by tpluscode** [comment]
Guess I forgot about something 🤔

**Comment by martinmaillard** [comment]
Hum, still need to merge master in. I'll do it right away

**Pull request merged**
