### PR TITLE
feat: add dataCube:identifierColumn to dimension table

### LINKED ISSUE #141: Dimension table: List of columns extracted from the `identifierTemplate`.
[...] it would be great if, for each `Table`, I could the list of columns extracted from the `identifierTemplate`.

_Originally posted by @martinmaillard in https://github.com/zazuko/data-cube-curation/pull/134#issuecomment-563262936_

### PR DESCRIPTION
**Pull request by tpluscode**
fixes #141

### CODE REVIEW

**Comment by martinmaillard** [comment]
One thing I noticed is that the property contains a value when there is only one column, and an array when there are multiple. I can handle it on the frontend, but it's not ideal. So if it's easy to always return a list of values, that would be better.

**Comment by martinmaillard** [comment]
Any way I could also get the `schema:name` of the column and the `Column` type?

**Comment by tpluscode** [comment]
> a value when there is only one column, and an array when there are multiple

Unfortunately that is kind of how RDF works in all places. RDF Lists are not really ideal here. 
I'd suggest using the [`getArray`](https://alcaeus.hydra.how/latest/representations/resource-properties.html#get-and-getarray) helper to always wrap single object as an array.

> Any way I could also get the schema:name of the column and the Column type?

Sure, but won't you already have the column data in the application state?

**Comment by martinmaillard** [comment]
> I'd suggest using the getArray helper to always wrap single object as an array

Nice! I forgot about `getArray` :)

> Sure, but won't you already have the column data in the application state?

I should, but it makes my life more complicated. If you prefer, I can use what I have.

**Comment by tpluscode** [comment]
> it makes my life more complicated

Not the intention. Of course, let me add those triples!

**Pull request merged**
