### PR TITLE
fix: replace rdf:predicate with property template completely

### PR DESCRIPTION
**Pull request by tpluscode**
Query to migrate the `READ_MODEL` store. Already fired on the staging environment

```sparql
PREFIX dataCube: <https://rdf-cube-curation.described.at/> 

DELETE
{
  ?attr rdf:predicate ?predicate .
}
INSERT
{
  ?attr dataCube:propertyTemplate ?pStr .
}
WHERE
{
  ?attr a dataCube:Attribute ;
    rdf:predicate ?predicate .

  BIND (str(?predicate) as ?pStr)
}
```

### CODE REVIEW

**Comment by martinmaillard** [comment]
Is there a reason to support both `rdf:predicate` and `dataCube:propertyTemplate`? Since we don't have any production data yet, I feel like it's not worth complicating the code for this.

**Comment by tpluscode** [comment]
Yea, probably. Especially given what @ktk has just said...

**Comment by tpluscode** [comment]
Isn't that nice @martinmaillard . -50 lines

**Comment by martinmaillard** [comment]
Yay! :)

**Pull request merged**
