### PR TITLE
fix: do not fail on spaces in column names

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by martinmaillard** [comment]
It doesn't error anymore and the mapping looks OK, but when previewing the mapped data the column seems to be ignored: `table/{the column}/suffix` -> `http://project-base-uri/table//suffix`

**Comment by tpluscode** [comment]
Hm, I though it was fine but maybe I was not looking where I should have. In such case it must mean that rdf-csvw-parser does not correctly match the escaped template variables with column names.

@bergos ?

**Comment by martinmaillard** [comment]
I'm not sure what you changed, but it seems to work now.

Not so useful now but I went through the spec and I think the way to support spaces in column names is to define a `name` property for each column, and make it the percent-encoded value that we currently use for `title` (c.f. [column description](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dfn-column-description)). This `name` is what is used to reference columns in URI templates variables (c.f. [URI template property](https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dfn-uri-template-property)).

**Comment by tpluscode** [comment]
Interesting find. Yet it still ignores the actual requirements of URI Template spec.

I changed the output mapping so that the column names are not actually percent-encoded. I only encode them when the template is parsed. Otherwise they remain as provided by the UI/client. It works but likely we're just taking advantage of loose implementation of the involved specs.

**Comment by martinmaillard** [comment]
> Yet it still ignores the actual requirements of URI Template spec.

I what way does it ignore the requirements? I couldn't find the issue in the [URI template spec](https://tools.ietf.org/html/rfc6570#section-2.3)

**Comment by tpluscode** [comment]
By overlooking the fact that variables can pretty much only be plain ASCII and no whitespace

**Comment by martinmaillard** [comment]
From https://www.w3.org/TR/2015/REC-tabular-metadata-20151217/#dfn-column-description

> For ease of reference within URI template properties, column names are restricted as defined in Variables in [URI-TEMPLATE] with the additional provision that names beginning with "_" are reserved by this specification and must not be used within metadata documents.

Sounds like they didn't completely overlook that ;)

**Comment by tpluscode** [comment]
Ok, fair enough

**Comment by martinmaillard** [comment]
Do you want to add the `name` property or should we merge this as is? I'm fine either way.

**Comment by tpluscode** [comment]
Huh, I now read that section more closely and it says that the `titles` property MUST be percent-encoded. I think we should dedicate a separate issue to really get a grip on all that.

Let's keep as it is for now

**Comment by martinmaillard** [comment]
I also re-read the section and it's not clear to me if the `titles` MUST always be percent-encoded, or only when no `name` is defined (since the first `titles` will be used as `name`).

**Pull request merged**
