### PR TITLE
WIP: setting csvw's aboutUrl for output tables

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by martinmaillard** [comment]
Some things I noticed (maybe not everything is linked to this PR):
- The `baseUri` needs to end with `/`. Maybe we could detect this and add it if it's missing?
- If I create new attributes with a bare name (not a URI), they still end up like `"csvw:propertyUrl": "http://localhost:5678/my-property"` in the mapping. We should probably use `baseUri` here?
- `csvw:title` doesn't correspond to the correct column. Probably still the off-by-1 error that we noticed the other day?
- I know see the references between tables in the mapping, but not in the mapped data

**Comment by tpluscode** [comment]
Thanks

> The baseUri needs to end with /. Maybe we could detect this and add it if it's missing?

Good point. While a base URI might end in a `#` or anything else really, I realise that a bare domain like `http://example.com` does not make sense. Will add that slash in that case.

> If I create new attributes with a bare name (not a URI), they still end up like "csvw:propertyUrl": "http://localhost:5678/my-property" in the mapping. We should probably use baseUri here?

Yes. Let's do that in a separate PR?

> csvw:title doesn't correspond to the correct column. Probably still the off-by-1 error that we noticed the other day?

Which off-by-1 was that?

> I now see the references between tables in the mapping, but not in the mapped data

Hm, maybe the csvw is not correct somehow and not picked up by the parser. Or maybe caused by the column problem above.

**Comment by martinmaillard** [comment]
> Which off-by-1 was that?

`csvw:title` is wrong for all columns in the mapping, not sure what causes that.

**Comment by tpluscode** [comment]
Hey @martinmaillard. I corrected the remaining two problems you noticed. Feel free to merge when you've had a chance to take a look.

Let's deploy once this is merged

**Comment by martinmaillard** [comment]
Great! It seems to work now :)

Do you want to fix the tests before we merge?

**Comment by tpluscode** [comment]
Yes, sorry. Working on it right now. Will be done in no-time

**Pull request merged**
