### PR TITLE
feat(api): update table

### PR DESCRIPTION
**Pull request by tpluscode**

### CODE REVIEW

**Comment by martinmaillard** [comment]
I think the `identifierTemplate` is not validated when updating a table.

**Comment by tpluscode** [comment]
I added validation to update/creation of tables and also a revert on the project so that you don't get the "Fact table has already been selected" when it failed to actually create it

**Comment by martinmaillard** [comment]
Validation works now, but when creating a new fact table, I get the following error in the API and it returns 404:
```
2020-04-02T11:57:12.313Z dataCube:request:error Request failed: NotFoundError: at Object.getRepresentation (/.../data-cube-curation/api/lib/read-graphs/table/index.ts:17:11) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:93:5) at /.../data-cube-curation/api/lib/data-cube/table/createDimensionTable.ts:88:13
```

**Comment by tpluscode** [comment]
Ah, might be also why some tests failed. I'm about to look into that

**Comment by martinmaillard** [comment]
One more thing: if I remove a table's identifier template from the "update" form, the API sets it to the string `"null"`. The "create" form works properly.

**Pull request merged**
